.TH "Connection" 3 "Fri Oct 3 2014" "Version 0.3" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Connection \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Connection\&.h>\fP
.PP
Inherits \fBTransceiver\fP, and \fBSocketFd\fP\&.
.PP
Inherited by \fBTCPClientSocket\fP, and \fBUNIXClientSocket\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnection\fP (const int=0, const std::string taddr='')"
.br
.ti -1c
.RI "virtual \fB~Connection\fP ()"
.br
.ti -1c
.RI "int \fBsend\fP (const std::string)"
.br
.ti -1c
.RI "int \fBrecv\fP (std::string &, int)"
.br
.ti -1c
.RI "int \fBrecv\fP (char *, const unsigned, const int=-1)"
.br
.ti -1c
.RI "int \fBsend\fP (const char *, const unsigned, const int=-1)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBtargetaddr\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "unsigned int \fBsum\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file Connection\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Connection::Connection (const intfd = \fC0\fP, const std::stringtaddr = \fC''\fP)"

.PP
Definition at line 3 of file Connection\&.cpp\&.
.PP
References n, sum, targetaddr, and SocketFd::ufds\&.
.SS "Connection::~Connection ()\fC [virtual]\fP"

.PP
Definition at line 10 of file Connection\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int Connection::recv (std::string &out, intsize)"

.PP
Definition at line 42 of file Connection\&.cpp\&.
.PP
References n\&.
.PP
Referenced by main()\&.
.SS "int Connection::recv (char *buf, const unsignedsize, const int = \fC-1\fP)\fC [virtual]\fP"

.PP
Implements \fBTransceiver\fP\&.
.PP
Definition at line 33 of file Connection\&.cpp\&.
.PP
References WEADMACRO\&.
.SS "int Connection::send (const std::stringin)"

.PP
Definition at line 38 of file Connection\&.cpp\&.
.PP
Referenced by main()\&.
.SS "int Connection::send (const char *buf, const unsignedsize, const int = \fC-1\fP)\fC [virtual]\fP"

.PP
Implements \fBTransceiver\fP\&.
.PP
Definition at line 28 of file Connection\&.cpp\&.
.PP
References WEADMACRO\&.
.SH "Member Data Documentation"
.PP 
.SS "int Connection::n\fC [private]\fP"

.PP
Definition at line 18 of file Connection\&.h\&.
.PP
Referenced by Connection(), recv(), and TCPClientSocket::TCPClientSocket()\&.
.SS "unsigned int Connection::sum\fC [private]\fP"

.PP
Definition at line 19 of file Connection\&.h\&.
.PP
Referenced by Connection()\&.
.SS "std::string Connection::targetaddr"

.PP
Definition at line 23 of file Connection\&.h\&.
.PP
Referenced by Connection(), and TCPClientSocket::TCPClientSocket()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
