Connection
NAME
Connection -
SYNOPSIS
#include <Connection.h>
Inherits Transceiver, and SocketFd.
Inherited by TCPClientSocket, and UNIXClientSocket.
Public Member Functions
Connection (const int=0, const std::string taddr='')
virtual ~Connection ()
int recv (char *, const unsigned, const int=-1)
int send (const char *, const unsigned, const int=-1)
Public Attributes
std::string targetaddr
Private Member Functions
int _poll (const int=-1)
Private Attributes
int n
unsigned int sum
Additional Inherited Members
Detailed Description
Definition at line 13 of file Connection.h.
Constructor & Destructor Documentation
Connection::Connection (const intfd = 0, const std::stringtaddr = '')
Definition at line 3 of file Connection.cpp.
References n, sum, targetaddr, and SocketFd::ufds.
Connection::~Connection () [virtual]
Definition at line 10 of file Connection.cpp.
Member Function Documentation
int Connection::_poll (const intmsec = -1) [private]
Definition at line 42 of file Connection.cpp.
References SocketFd::ufds.
Referenced by recv(), and send().
int Connection::recv (char *buf, const unsignedsize, const intmsec = -1) [virtual]
Implements Transceiver.
Definition at line 35 of file Connection.cpp.
References _poll(), and WEADMACRO.
Referenced by stream_client(), and stream_server().
int Connection::send (const char *buf, const unsignedsize, const intmsec = -1) [virtual]
Implements Transceiver.
Definition at line 30 of file Connection.cpp.
References _poll(), and WEADMACRO.
Referenced by main(), stream_client(), and stream_server().
Member Data Documentation
int Connection::n [private]
Definition at line 17 of file Connection.h.
Referenced by Connection(), and TCPClientSocket::TCPClientSocket().
unsigned int Connection::sum [private]
Definition at line 18 of file Connection.h.
Referenced by Connection().
std::string Connection::targetaddr
Definition at line 22 of file Connection.h.
Referenced by Connection(), and TCPClientSocket::TCPClientSocket().
Author
Generated automatically by Doxygen for 0xSocket from the source code.