src/Example.cpp
NAME
src/Example.cpp -
SYNOPSIS
#include <iostream>
#include <Socket.h>
#include <string>
#include <sstream>
Macros
#define DEFAULTPORT 1234
#define DEFAULTMSGC 'Hello here Client'
#define DEFAULTMSGS 'Hello here Server'
#define DEFAULTUNIX 'echo_socket'
#define DEFAULTSERV '127.0.0.1'
Functions
void stream_server (ServerSocket &)
void stream_client (Connection &)
string ltrim (const string str)
Removes leading Spaces and Tabs.
string rtrim (const string str)
Removes trailing Spaces and Tabs.
string trim (const string str)
Removes leading and trailing Spaces and Tabs.
template<class T > T str2 (const string str)
Convert a String to a T Object.
void printusage (char *name)
prints usage info
int main (int argc, char *argv[])
Variables
static const char END_OF_MESSAGE = '\n'
Macro Definition Documentation
#define DEFAULTMSGC 'Hello here Client'
Definition at line 21 of file Example.cpp.
Referenced by main(), and stream_client().
#define DEFAULTMSGS 'Hello here Server'
Definition at line 22 of file Example.cpp.
Referenced by main(), and stream_server().
#define DEFAULTPORT 1234
Definition at line 20 of file Example.cpp.
Referenced by main().
#define DEFAULTSERV '127.0.0.1'
Definition at line 24 of file Example.cpp.
Referenced by main().
#define DEFAULTUNIX 'echo_socket'
Definition at line 23 of file Example.cpp.
Referenced by main().
Function Documentation
string ltrim (const stringstr)
Removes leading Spaces and Tabs. Removes leading Spaces and Tabs
Parameters:
str String to
Returns:
trimmed String
Definition at line 382 of file Example.cpp.
Referenced by trim().
int main (intargc, char *argv[])
This is the End ... no wait ... the opposite HTTP Client
UDP Server
TCP Server
UNIX Server
UDP Client
TCP Client
UNIX Client
Definition at line 49 of file Example.cpp.
References DEFAULTMSGC, DEFAULTMSGS, DEFAULTPORT, DEFAULTSERV, DEFAULTUNIX, printusage(), UDPSocket::recv(), Connection::send(), UDPSocket::send(), stream_client(), stream_server(), and trim().
void printusage (char *name)
prints usage info prints usage info
Parameters:
name of the executable
Definition at line 31 of file Example.cpp.
Referenced by main().
string rtrim (const stringstr)
Removes trailing Spaces and Tabs. Removes trailing Spaces and Tabs
Parameters:
str String to
Returns:
trimmed String
Definition at line 368 of file Example.cpp.
Referenced by trim().
template<class T > T str2 (const stringstr)
Convert a String to a T Object. This Function tries to convert any string into any Type the Template Function was called with.
Parameters:
 return
Definition at line 356 of file Example.cpp.
void stream_client (Connection &con)
sends ans recv some data over a Connection We recv one Byte at a time till we get the End of Message (EOM) Character or recv detects an error and return a value less then Zero
If you want to recv larger amounts of Data make sure not to expect to much otherwise recv will block indefinetly for the remaining Bytes ... so design your Protocol whisely.
Definition at line 301 of file Example.cpp.
References DEFAULTMSGC, END_OF_MESSAGE, Connection::recv(), and Connection::send().
Referenced by main().
void stream_server (ServerSocket &sock)
Accept Connections on ServerSockets and sends ans recv some data We recv one Byte at a time till we get the End of Message (EOM) Character or recv detects an error and return a value less then Zero
If you want to recv larger amounts of data make sure not to miscalculate. Otherwise recv will block indefinetly for the remaining Bytes ... so design your protocol whisely.
Definition at line 231 of file Example.cpp.
References ServerSocket::accept(), DEFAULTMSGS, END_OF_MESSAGE, Connection::recv(), Connection::send(), and SocketFd::setTimeout().
Referenced by main().
string trim (const stringstr)
Removes leading and trailing Spaces and Tabs. Removes leading and trailing Spaces and Tabs
Parameters:
str String to
Returns:
trimmed String
Definition at line 396 of file Example.cpp.
References ltrim(), and rtrim().
Referenced by main().
Variable Documentation
const char END_OF_MESSAGE = '\n' [static]
Definition at line 18 of file Example.cpp.
Referenced by stream_client(), and stream_server().
Author
Generated automatically by Doxygen for 0xSocket from the source code.