examples/http_client.cpp
NAME
examples/http_client.cpp -
SYNOPSIS
#include <iostream>
#include <Socket.h>
#include <string>
#include <cstdlib>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (intargc, char *argv[])
Definition at line 8 of file http_client.cpp.
References Connection::recv(), Connection::send(), and SocketFd::setTimeout().
Author
Generated automatically by Doxygen for 0xSocket from the source code.