.TH "include/ServerSocket.h" 3 "Fri Oct 3 2014" "Version 0.3" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ServerSocket.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Connection\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBServerSocket\fP"
.br
.RI "\fINot instanziable BaseClass for all \fBServerSocket\fP Classes\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
