.TH "ServerSocket" 3 "Thu Oct 2 2014" "Version 0.2" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServerSocket \- 
.PP
Not instanziable BaseClass for all \fBServerSocket\fP Classes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ServerSocket\&.h>\fP
.PP
Inherited by \fBTCPServerSocket\fP, and \fBUNIXServerSocket\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ServerSocket\fP ()"
.br
.ti -1c
.RI "virtual \fBConnection\fP * \fBaccept\fP ()=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBServerSocket\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Not instanziable BaseClass for all \fBServerSocket\fP Classes\&. 

Not instanziable BaseClass for all \fBServerSocket\fP Classes\&. Must provides an \fBaccept()\fP function that will return a \fBConnection\fP Object 
.PP
Definition at line 11 of file ServerSocket\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ServerSocket::ServerSocket ()\fC [protected]\fP"

.PP
Definition at line 3 of file ServerSocket\&.cpp\&.
.SS "ServerSocket::~ServerSocket ()\fC [virtual]\fP"

.PP
Definition at line 6 of file ServerSocket\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBConnection\fP* ServerSocket::accept ()\fC [pure virtual]\fP"

.PP
Implemented in \fBTCPServerSocket\fP, and \fBUNIXServerSocket\fP\&.
.PP
Referenced by stream_server()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
