.TH "include/Socket.h" 3 "Thu Oct 2 2014" "Version 0.2" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Socket.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <TCPServerSocket\&.h>\fP
.br
\fC#include <TCPClientSocket\&.h>\fP
.br
\fC#include <UNIXServerSocket\&.h>\fP
.br
\fC#include <UNIXClientSocket\&.h>\fP
.br
\fC#include <UDPServerSocket\&.h>\fP
.br
\fC#include <UDPClientSocket\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
