.TH "include/SocketFd.h" 3 "Thu Oct 2 2014" "Version 0.2" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/SocketFd.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <poll\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSocketFd\fP"
.br
.RI "\fINot initalizable BaseClass for SocketFileDescriptor\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
