examples/tcp_server.cpp
NAME
examples/tcp_server.cpp -
SYNOPSIS
#include <iostream>
#include <Socket.h>
#include <string>
#include <cstdlib>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (intargc, char *argv[])
Definition at line 10 of file tcp_server.cpp.
References TCPServerSocket::accept(), Connection::recv(), Connection::send(), and SocketFd::setTimeout().
Author
Generated automatically by Doxygen for 0xSocket from the source code.