.TH "examples/tcp_server.cpp" 3 "Fri Oct 3 2014" "Version 0.3" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples/tcp_server.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <Socket\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cstdlib>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Definition at line 10 of file tcp_server\&.cpp\&.
.PP
References TCPServerSocket::accept(), Connection::recv(), Connection::send(), and SocketFd::setTimeout()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
