.TH "include/TCPSocket.h" 3 "Fri Oct 3 2014" "Version 0.3" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/TCPSocket.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <netdb\&.h>\fP
.br
\fC#include <bits/socket\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTCPSocket\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
