.TH "TCPSocket" 3 "Thu Oct 2 2014" "Version 0.2" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TCPSocket \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TCPSocket\&.h>\fP
.PP
Inherited by \fBTCPClientSocket\fP, and \fBTCPServerSocket\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~TCPSocket\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTCPSocket\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBrv\fP"
.br
.ti -1c
.RI "socklen_t \fBslen\fP"
.br
.ti -1c
.RI "addrinfo \fBhints\fP"
.br
.ti -1c
.RI "addrinfo * \fBservinfo\fP"
.br
.ti -1c
.RI "addrinfo * \fBp\fP"
.br
.ti -1c
.RI "sockaddr_storage \fBtheir_addr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Non constructable BaseClass for TCP Sockets just because they share some structs This is purely for internal use 
.PP
Definition at line 15 of file TCPSocket\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TCPSocket::TCPSocket ()\fC [protected]\fP"

.PP
Definition at line 6 of file TCPSocket\&.cpp\&.
.PP
References p, rv, servinfo, and slen\&.
.SS "TCPSocket::~TCPSocket ()\fC [virtual]\fP"

.PP
Definition at line 3 of file TCPSocket\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "addrinfo TCPSocket::hints\fC [protected]\fP"

.PP
Definition at line 19 of file TCPSocket\&.h\&.
.PP
Referenced by TCPClientSocket::TCPClientSocket(), and TCPServerSocket::TCPServerSocket()\&.
.SS "addrinfo * TCPSocket::p\fC [protected]\fP"

.PP
Definition at line 19 of file TCPSocket\&.h\&.
.PP
Referenced by TCPClientSocket::TCPClientSocket(), TCPServerSocket::TCPServerSocket(), and TCPSocket()\&.
.SS "int TCPSocket::rv\fC [protected]\fP"

.PP
Definition at line 17 of file TCPSocket\&.h\&.
.PP
Referenced by TCPClientSocket::TCPClientSocket(), TCPServerSocket::TCPServerSocket(), and TCPSocket()\&.
.SS "addrinfo * TCPSocket::servinfo\fC [protected]\fP"

.PP
Definition at line 19 of file TCPSocket\&.h\&.
.PP
Referenced by TCPClientSocket::TCPClientSocket(), TCPServerSocket::TCPServerSocket(), and TCPSocket()\&.
.SS "socklen_t TCPSocket::slen\fC [protected]\fP"

.PP
Definition at line 18 of file TCPSocket\&.h\&.
.PP
Referenced by TCPServerSocket::accept(), and TCPSocket()\&.
.SS "sockaddr_storage TCPSocket::their_addr\fC [protected]\fP"

.PP
Definition at line 20 of file TCPSocket\&.h\&.
.PP
Referenced by TCPServerSocket::accept()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
