.TH "include/Transceiver.h" 3 "Thu Oct 2 2014" "Version 0.2" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Transceiver.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTransceiver\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
