.TH "Transceiver" 3 "Fri Oct 3 2014" "Version 0.3" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transceiver \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Transceiver\&.h>\fP
.PP
Inherited by \fBConnection\fP, and \fBUDPSocket\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Transceiver\fP ()"
.br
.ti -1c
.RI "virtual int \fBsend\fP (const char *, const unsigned, const int=0)=0"
.br
.ti -1c
.RI "virtual int \fBrecv\fP (char *, const unsigned, const int=0)=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBTransceiver\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
virtual BaseClass for Classes that should provide a \fBsend()\fP and \fBrecv()\fP method 
.PP
Definition at line 7 of file Transceiver\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Transceiver::Transceiver ()\fC [protected]\fP"

.PP
Definition at line 3 of file Transceiver\&.cpp\&.
.SS "Transceiver::~Transceiver ()\fC [virtual]\fP"

.PP
Definition at line 6 of file Transceiver\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual int Transceiver::recv (char *, const unsigned, const int = \fC0\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBUDPSocket\fP, and \fBConnection\fP\&.
.SS "virtual int Transceiver::send (const char *, const unsigned, const int = \fC0\fP)\fC [pure virtual]\fP"

.PP
Implemented in \fBUDPSocket\fP, and \fBConnection\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
