.TH "UDPClientSocket" 3 "Fri Oct 3 2014" "Version 0.3" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UDPClientSocket \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UDPClientSocket\&.h>\fP
.PP
Inherits \fBUDPSocket\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUDPClientSocket\fP (const std::string addr, const unsigned int port)"
.br
.RI "\fIconstruct \fBUDPClientSocket\fP \fP"
.ti -1c
.RI "virtual \fB~UDPClientSocket\fP ()"
.br
.RI "\fIdoes nothing \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBUDPClientSocket\fP is read to \fBsend()\fP and \fBrecv()\fP data after construction if construction failes a runtime_error is thrown BaseCöass is \fBConnection\fP 
.PP
Definition at line 22 of file UDPClientSocket\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UDPClientSocket::UDPClientSocket (const std::stringaddr, const unsigned intport)"

.PP
construct \fBUDPClientSocket\fP construct \fBUDPClientSocket\fP 
.PP
\fBParameters:\fP
.RS 4
\fIaddr\fP The Address of the host 
.br
\fIport\fP The Port the host is listening on 
.RE
.PP

.PP
Definition at line 3 of file UDPClientSocket\&.cpp\&.
.PP
References UDPSocket::hints, UDPSocket::p, UDPSocket::rv, UDPSocket::servinfo, and SocketFd::ufds\&.
.SS "UDPClientSocket::~UDPClientSocket ()\fC [virtual]\fP"

.PP
does nothing does nothing 
.PP
Definition at line 41 of file UDPClientSocket\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
