.TH "UDPSocket" 3 "Fri Oct 3 2014" "Version 0.3" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UDPSocket \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UDPSocket\&.h>\fP
.PP
Inherits \fBSocketFd\fP, and \fBTransceiver\fP\&.
.PP
Inherited by \fBUDPClientSocket\fP, and \fBUDPServerSocket\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBsend\fP (const char *buf, const unsigned size, int=0)"
.br
.RI "\fISends Data\&. \fP"
.ti -1c
.RI "int \fBrecv\fP (char *buf, const unsigned size, int=0)"
.br
.RI "\fIRecv Data\&. \fP"
.ti -1c
.RI "virtual \fB~UDPSocket\fP ()"
.br
.RI "\fIfrees some structs \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBUDPSocket\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBrv\fP"
.br
.ti -1c
.RI "addrinfo \fBhints\fP"
.br
.ti -1c
.RI "addrinfo * \fBservinfo\fP"
.br
.ti -1c
.RI "addrinfo * \fBp\fP"
.br
.ti -1c
.RI "sockaddr_storage \fBtheir_addr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
virtual baseclass for UDP Sockets implements \fBsend()\fP and \fBrecv()\fP for Client and Server Sockets and holds some structs used by both 
.PP
Definition at line 18 of file UDPSocket\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UDPSocket::UDPSocket ()\fC [protected]\fP"

.PP
Definition at line 3 of file UDPSocket\&.cpp\&.
.PP
References p, rv, and servinfo\&.
.SS "UDPSocket::~UDPSocket ()\fC [virtual]\fP"

.PP
frees some structs frees some structs 
.PP
Definition at line 9 of file UDPSocket\&.cpp\&.
.PP
References servinfo\&.
.SH "Member Function Documentation"
.PP 
.SS "int UDPSocket::recv (char *buf, const unsignedsize, int = \fC0\fP)\fC [virtual]\fP"

.PP
Recv Data\&. Recv Data 
.PP
\fBParameters:\fP
.RS 4
\fIbuf\fP recv buffer 
.br
\fIsize\fP nb of bytes to recv 
.br
\fI???\fP 
.RE
.PP

.PP
Implements \fBTransceiver\fP\&.
.PP
Definition at line 17 of file UDPSocket\&.cpp\&.
.PP
References p, and SocketFd::ufds\&.
.PP
Referenced by main()\&.
.SS "int UDPSocket::send (const char *buf, const unsignedsize, int = \fC0\fP)\fC [virtual]\fP"

.PP
Sends Data\&. Sends Data 
.PP
\fBParameters:\fP
.RS 4
\fIbuf\fP send buffer 
.br
\fIsize\fP nb of bytes to send 
.br
\fI???\fP 
.RE
.PP

.PP
Implements \fBTransceiver\fP\&.
.PP
Definition at line 13 of file UDPSocket\&.cpp\&.
.PP
References p, and SocketFd::ufds\&.
.PP
Referenced by main()\&.
.SH "Member Data Documentation"
.PP 
.SS "addrinfo UDPSocket::hints\fC [protected]\fP"

.PP
Definition at line 21 of file UDPSocket\&.h\&.
.PP
Referenced by UDPClientSocket::UDPClientSocket(), and UDPServerSocket::UDPServerSocket()\&.
.SS "addrinfo * UDPSocket::p\fC [protected]\fP"

.PP
Definition at line 21 of file UDPSocket\&.h\&.
.PP
Referenced by recv(), send(), UDPClientSocket::UDPClientSocket(), UDPServerSocket::UDPServerSocket(), and UDPSocket()\&.
.SS "int UDPSocket::rv\fC [protected]\fP"

.PP
Definition at line 20 of file UDPSocket\&.h\&.
.PP
Referenced by UDPClientSocket::UDPClientSocket(), UDPServerSocket::UDPServerSocket(), and UDPSocket()\&.
.SS "addrinfo * UDPSocket::servinfo\fC [protected]\fP"

.PP
Definition at line 21 of file UDPSocket\&.h\&.
.PP
Referenced by UDPClientSocket::UDPClientSocket(), UDPServerSocket::UDPServerSocket(), UDPSocket(), and ~UDPSocket()\&.
.SS "sockaddr_storage UDPSocket::their_addr\fC [protected]\fP"

.PP
Definition at line 22 of file UDPSocket\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
