examples/unix_server.cpp
NAME
examples/unix_server.cpp -
SYNOPSIS
#include <iostream>
#include <Socket.h>
#include <string>
#include <cstdlib>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (intargc, char *argv[])
Definition at line 10 of file unix_server.cpp.
References UNIXServerSocket::accept(), Connection::recv(), Connection::send(), and SocketFd::setTimeout().
Author
Generated automatically by Doxygen for 0xSocket from the source code.