.TH "include/UNIXServerSocket.h" 3 "Thu Oct 2 2014" "Version 0.2" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/UNIXServerSocket.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/un\&.h>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <SocketFd\&.h>\fP
.br
\fC#include <Connection\&.h>\fP
.br
\fC#include <ServerSocket\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUNIXServerSocket\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
