.TH "UNIXServerSocket" 3 "Thu Oct 2 2014" "Version 0.2" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNIXServerSocket \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UNIXServerSocket\&.h>\fP
.PP
Inherits \fBSocketFd\fP, and \fBServerSocket\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUNIXServerSocket\fP (const char *path)"
.br
.RI "\fIconstruct a unix server socket \fP"
.ti -1c
.RI "virtual \fB~UNIXServerSocket\fP ()"
.br
.ti -1c
.RI "\fBConnection\fP * \fBaccept\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBlast_new_sock\fP"
.br
.ti -1c
.RI "sockaddr_un \fBlocal\fP"
.br
.ti -1c
.RI "sockaddr_un \fBremote\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBUNIXServerSocket\fP provides a means for UNIX Clients to be Accepted with the \fBaccept()\fP methode it provides if the construction failes and the socketfile can not be accessed the constructor will throw a runtime_error 
.PP
Definition at line 28 of file UNIXServerSocket\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UNIXServerSocket::UNIXServerSocket (const char *path)"

.PP
construct a unix server socket construct a unix server socket 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP Path to UNIX Socket File 
.RE
.PP

.PP
Definition at line 3 of file UNIXServerSocket\&.cpp\&.
.PP
References last_new_sock, local, and SocketFd::ufds\&.
.SS "UNIXServerSocket::~UNIXServerSocket ()\fC [virtual]\fP"

.PP
Definition at line 32 of file UNIXServerSocket\&.cpp\&.
.PP
References local\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBConnection\fP * UNIXServerSocket::accept ()\fC [virtual]\fP"

.PP
Implements \fBServerSocket\fP\&.
.PP
Definition at line 36 of file UNIXServerSocket\&.cpp\&.
.PP
References last_new_sock, remote, and SocketFd::ufds\&.
.SH "Member Data Documentation"
.PP 
.SS "int UNIXServerSocket::last_new_sock\fC [private]\fP"

.PP
Definition at line 31 of file UNIXServerSocket\&.h\&.
.PP
Referenced by accept(), and UNIXServerSocket()\&.
.SS "sockaddr_un UNIXServerSocket::local\fC [private]\fP"
sockfile structs 
.PP
Definition at line 35 of file UNIXServerSocket\&.h\&.
.PP
Referenced by UNIXServerSocket(), and ~UNIXServerSocket()\&.
.SS "sockaddr_un UNIXServerSocket::remote\fC [private]\fP"

.PP
Definition at line 35 of file UNIXServerSocket\&.h\&.
.PP
Referenced by accept()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
