.TH "include/UNIXClientSocket.h" 3 "Fri Oct 3 2014" "Version 0.3" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/UNIXClientSocket.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/un\&.h>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <string>\fP
.br
\fC#include <Connection\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUNIXClientSocket\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
