.TH "UNIXClientSocket" 3 "Thu Oct 2 2014" "Version 0.2" "0xSocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNIXClientSocket \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UNIXClientSocket\&.h>\fP
.PP
Inherits \fBConnection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUNIXClientSocket\fP (const char *path)"
.br
.RI "\fIconstruct \fBUNIXClientSocket\fP throws runtime_error on failure \fP"
.ti -1c
.RI "virtual \fB~UNIXClientSocket\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "sockaddr_un \fBremote\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A \fBUNIXClientSocket\fP establishes a connection on construct Afterwards it can be used like a \fBConnection\fP Object\&. It directly provides \fBsend()\fP and \fBrecv()\fP functions on init/connection error the Constructor throws a std::runtime_error 
.PP
Definition at line 21 of file UNIXClientSocket\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UNIXClientSocket::UNIXClientSocket (const char *path)"

.PP
construct \fBUNIXClientSocket\fP throws runtime_error on failure construct \fBUNIXClientSocket\fP throws runtime_error on failure 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP Path to socket file 
.RE
.PP

.PP
Definition at line 3 of file UNIXClientSocket\&.cpp\&.
.PP
References remote, and SocketFd::ufds\&.
.SS "UNIXClientSocket::~UNIXClientSocket ()\fC [virtual]\fP"

.PP
Definition at line 22 of file UNIXClientSocket\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "sockaddr_un UNIXClientSocket::remote\fC [private]\fP"

.PP
Definition at line 26 of file UNIXClientSocket\&.h\&.
.PP
Referenced by UNIXClientSocket()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for 0xSocket from the source code\&.
